In [6]:
from All_Functions import *
import sympy as sp
import numpy as np

N_PC = 5

matrices, F, Variables = Build_matrices(N_PC)

for i in range(0,N_PC+1):
    for j in range(0,N_PC+1):
        AB = matrices[i]@matrices[j]
        BA = matrices[j]@matrices[i]
        print(f"[A{i},A{j}]:")
        print(AB-BA)
        print("-"*50)

[A0,A0]:
[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]
--------------------------------------------------
[A0,A1]:
[[0 8/9 0 0 0 0]
 [-8/9 0 16/225 0 0 0]
 [0 -16/225 0 24/1225 0 0]
 [0 0 -24/1225 0 32/3969 0]
 [0 0 0 -32/3969 0 40/9801]
 [0 0 0 0 -40/9801 0]]
--------------------------------------------------
[A0,A2]:
[[0 0 16/25 0 0 0]
 [0 0 0 16/245 0 0]
 [-16/25 0 0 0 32/1575 0]
 [0 -16/245 0 0 0 160/17787]
 [0 0 -32/1575 0 0 0]
 [0 0 0 -160/17787 0 0]]
--------------------------------------------------
[A0,A3]:
[[0 0 0 24/49 0 0]
 [0 0 8/175 0 32/567 0]
 [0 -8/175 0 32/3675 0 16/847]
 [-24/49 0 -32/3675 0 16/4851 0]
 [0 -32/567 0 -16/4851 0 160/99099]
 [0 0 -16/847 0 -160/99099 0]]
--------------------------------------------------
[A0,A4]:
[[0 0 0 0 32/81 0]
 [0 0 0 64/1323 0 160/3267]
 [0 0 0 0 64/6237 0]
 [0 -64/1323 0 0 0 320/77077]
 [-32/81 0 -64/6237 0 0 0]
 [0 -160/3267 0 -320/77077 0 0]]
-----------------------------------------